name: clickclinician
description: ClickClinician mobile therapist application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.11+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  flutter_appauth: ^6.0.0
  flutter_secure_storage: ^9.2.2
  google_maps_flutter: ^2.3.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  geolocator: ^13.0.1
  intl: ^0.19.0
  shared_preferences: ^2.1.2
  webview_flutter: ^4.2.2
  webview_flutter_wkwebview: ^3.4.4
  webview_flutter_android: ^3.7.1
  device_info_plus: ^10.1.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.2
  package_info_plus: ^8.0.2
  crossplat_objectid: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.2.2
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.3
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles.json
#    - assets/well-known/assetlinks.json
