// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv8cSjSHdumeA9YnqWOjh9qB_ZApfbuRU',
    appId: '1:529879536502:web:4426444933cd3d60576057',
    messagingSenderId: '529879536502',
    projectId: 'click-clinician--1551198098946',
    authDomain: 'click-clinician-1551198098946.firebaseapp.com',
    databaseURL: 'https://click-clinician-1551198098946.firebaseio.com',
    storageBucket: 'click-clinician--1551198098946.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_gdsit1qEKCsPPWfXLrRkPTL5wiW73E',
    appId: '1:529879536502:android:59eed802f380e80e576057',
    messagingSenderId: '529879536502',
    projectId: 'click-clinician--1551198098946',
    databaseURL: 'https://click-clinician-1551198098946.firebaseio.com',
    storageBucket: 'click-clinician--1551198098946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUATkJA1UqbGntAQ7uMF0CjvUbEanmxwA',
    appId: '1:529879536502:ios:69017f11f042dfc1576057',
    messagingSenderId: '529879536502',
    projectId: 'click-clinician--1551198098946',
    databaseURL: 'https://click-clinician-1551198098946.firebaseio.com',
    storageBucket: 'click-clinician--1551198098946.appspot.com',
    iosClientId:
        '529879536502-25sgju5kkcg7864s1crt11srl2o96a5q.apps.googleusercontent.com',
    iosBundleId: 'com.clickclinician.mobile',
  );
}
